language: objective-c
osx_image: xcode7.3
podfile: ios/playground/Podfile
cache:
  bundler: true
  cocoapods: true
  directories:
    - node_modules
branches:
  except:
    - doc
    - example
before_script:
  - git clone https://github.com/gurisxie/weex-commit-ci.git
script: 
  #- sh ci-commit-ios
addons:
  artifacts: true