language: objective-c
osx_image: xcode7.3
cache:
  directories:
  - node_modules # NPM packages

branches:
  except:
    - doc
    - example

before_script:

script: 
  - sh ci-commit-ios

after_script: 

addons:
  artifacts: true
