language: objective-c
osx_image: xcode7.3
podfile: ios/playground/Podfile
cache:
  bundler: true
  cocoapods: true
  directories:
    - node_modules
branches:
  except:
    - doc
    - example
script: 
  - sh ci-commit-ios
addons:
  artifacts: true