#!/usr/bin/env bash
echo "************************ ci-ios start ************************"

weexPath=`pwd`
toolPath=${weexPath}/test/tools
homePath=/home/travis
echo "  tested root dir: " ${weexPath}

echo "----------------------------start：run env clear----------------------------"
cd ${weexPath}
sh ci-daily-envClear
echo "----------------------------finish：run env clear----------------------------"

echo "************************ build tested app ************************"
cd ${weexPath}/ios/playground

pod update

xcodebuild -scheme WeexUITestDemo -destination "name=iPhone 6" -workspace WeexDemo.xcworkspace -configuration Debug clean build
rc=$?
if [[ $rc != 0 ]] ; then
    echo "ios run build app: ios run build app failure,break ios running~ " >> ${resultPath}/run-result.log
    exit $rc
fi

cd ${toolPath}
src1=${weexPath}/package.json
src2=${homePath}/Documents/weex-npm/package.json

echo ${src2}

isNoChange=True
if [ ! -f "$src2" ]; then 
	isNoChange=False
	mkdir ${homePath}/Documents/weex-npm
	mkdir ${homePath}/Documents/weex-npm/src
	mkdir ${homePath}/Documents/weex-npm/bin
else
	isNoChange=`python packageJsonCompare.py -src1=${src1} -src2=${src2}`
	if [[ $isNoChange != False ]] ; then
	    src1=${weexPath}/src/js-framework/package.json
	    src2=$HOME/Documents/weex-npm/src/js-framework/package.json
	    isNoChange=`python packageJsonCompare.py -src1=${src1} -src2=${src2}`
	    if [[ $isNoChange != False ]] ; then
	        src1=${weexPath}/src/h5-render/package.json
	        src2=$HOME/Documents/weex-npm/src/h5-render/package.json
	        isNoChange=`python packageJsonCompare.py -src1=${src1} -src2=${src2}`
	    fi
	fi 
fi

cd ${weexPath}
if [[ $isNoChange == False ]] ; then
    echo "isNoChange:"${isNoChange}"，will npm install~"
    cp package.json $HOME/Documents/weex-npm/package.json
    cp src/h5-render/package.json $HOME/Documents/weex-npm/src/h5-render/package.json
    cp src/js-framework/package.json $HOME/Documents/weex-npm/src/js-framework/package.json
    rm -rf $HOME/Documents/weex-npm/bin
    cp -r bin $HOME/Documents/weex-npm/bin
    cd $HOME/Documents/weex-npm/
    npm install
    rc=$?
    if [[ $rc != 0 ]] ; then
        echo "npm install:npm install failure,break flow running~ " >> ${resultPath}/run-result.log
        exit $rc
    fi 
fi 
echo "isNoChange:"${isNoChange}

cd ${weexPath}
#TODO 比较package.json
ln -s $HOME/Documents/weex-npm/node_modules ./node_modules
ln -s $HOME/Documents/weex-npm/src/js-framework/node_modules/ ./src/js-framework/node_modules
ln -s $HOME/Documents/weex-npm/src/h5-render/node_modules/ ./src/h5-render/node_modules

npm run build
rc=$?
if [[ $rc != 0 ]] ; then
    echo "npm run build:run build failure,break flow running~ " >> ${resultPath}/run-result.log
    exit $rc
fi 

echo "                                Start local server"
#npm install weex-transformer@0.3.1
node ./node_modules/weex-transformer/bin/transformer.js test/tc-h5/*.we -o test/build
rc=$?
if [[ $rc != 0 ]] ; then
    echo "transform we to js:transform we to js failure,break flow running~ " >> ${resultPath}/run-result.log
    exit $rc
fi 

(npm run serve & echo "start npm run serve")

echo "************************ prepare for uitest ************************"
appPath=${weexPath}"/ios/playground/DerivedData/WeexDemo/Build/Products/Debug-iphonesimulator/WeexUITestDemo.app"
instruments -s devices > ./_temp.log
PREFIX="iPhone 6s"
cat ./_temp.log | while read line
do 
    if [[ $line == $PREFIX* ]]
    then
    	echo $line | sed 's/\(.*\)\[\(.*\)\]\(.*\)/\2/g' > ./_temp.log
        break
    fi
done
deviceName=`cat ./_temp.log`
rm -rf ./_temp.log

echo "关闭模拟器"
killall Simulator
sleep 5
echo "启动指定模拟器"
xcrun instruments -w ${deviceName}
sleep 5
echo "安装测试包"
xcrun simctl install booted ${appPath}

echo "************************ Start Sword Server ************************"
cd ${weexPath}/test/ios/sword.ios.server.start/bin/
rm -rf instrument*.trace
(sh start-server &) 

echo "************************ start uitest ************************"
cd ${weexPath}/test/ios/sword.ios.weex.test/
mkdir ${weexPath}/test/ios/sword.ios.weex.test/target

picSaveDir=${weexPath}"test/ios/pic-compare/"

mvn test -Dtest=sword.ios.app.test.iOSWXAHrefTest#testScreen_TC_AHref_Event_Test -DpicSaveDir=${picSaveDir} -DdeviceUuid=${deviceName} -DtestAppPath=${appPath}



